name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Website
        run: curl -I https://svc-payroll.vercel.app
